services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Teste@Teste123"
      ACCEPT_EULA: "Y"
    networks:
      - app-network

  products:
    build:
      context: .
      dockerfile: ../Products/Dockerfile
    container_name: products
    ports:
      - "5000:80"
    networks:
      - app-network
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80

networks:
  app-network:
